version: '3.3'

services:
  nginx:
    container_name: nginx
    image: linuxserver/letsencrypt
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.config/letsencrypt:/config
      - ./.config/nginx.conf:/config/nginx/site-confs/default
      - ./.config/ssl.conf:/config/nginx/ssl.conf
    depends_on:
      - portfolio-website
    networks:
      - frontend
    environment:
      - PUID=1001 # get on dockerhost through command "id <user>""
      - PGID=1001
      - EMAIL=erik@eriksanne.com
      - URL=eriksanne.com
      - SUBDOMAINS=www
      - TZ=Europe/London
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      # - STAGING=true # this should be uncommented when testing for initial success, to avoid some rate limiting

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./.config/certbot/conf:/etc/letsencrypt
      - ./.config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  portfolio-website:
    container_name: portfolio-website
    build: ./client
    restart: always
    expose:
      - "8080"
    networks:
      - frontend
    environment:
      - PORT=8080
      - NODE_ENV=production

networks:
  frontend:
